Repository sonic-net/sonic-platform-daemons, pull requests merged in 2020-06, with the labels that each got.

#58 [thermalctld] Fix invalid warning status
  sonic-thermalctld/scripts/thermalctld
Labels: Bug

#57 [MultiDB] should use multiDB API
  sonic-ledd/scripts/ledd
  sonic-psud/scripts/psud
  sonic-syseepromd/scripts/syseepromd
  sonic-thermalctld/scripts/thermalctld
  sonic-xcvrd/scripts/xcvrd
Labels: Request for 201911 Branch

#62 [xcvrd] Tweak some transceiver info key names
  sonic-xcvrd/scripts/xcvrd
Labels: Enhancement, Request for 201911 Branch
