Repository sonic-net/sonic-platform-daemons, pull requests merged in 2021-06, with the labels that each got.

#191 Replace swsssdk.SonicV2Connector with swsscommon implementation
  sonic-pcied/scripts/pcied
Labels: Cleanup, pcied

#194 [CI] sonic-config-engine now depends on SONiC YANG packages
  azure-pipelines.yml
Labels: Bug, CI

#193 [xcvrd] Force cleanup of chassis global variable on deinit
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: Request for 202012 Branch

#189 Refactor Pcied and add unittest
  sonic-pcied/pytest.ini
  sonic-pcied/scripts/pcied
  sonic-pcied/setup.cfg
  sonic-pcied/setup.py
  sonic-pcied/tests/__init__.py
  sonic-pcied/tests/mock_platform.py
  sonic-pcied/tests/mocked_libs/swsscommon/__init__.py
  sonic-pcied/tests/mocked_libs/swsscommon/swsscommon.py
  sonic-pcied/tests/test_DaemonPcied.py
  sonic-pcied/tests/test_pcied.py
Labels: Request for 202012 Branch

#184 [xcvrd] Add bitmap support for SFP error event
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd_utilities/sfp_status_helper.py
  sonic-xcvrd/xcvrd/xcvrd_utilities/y_cable_helper.py
Labels: Enhancement, xcvrd

#175 Collect asic info and store in CHASSIS_STATE_DB
  sonic-chassisd/scripts/chassisd
  sonic-chassisd/tests/mock_platform.py
  sonic-chassisd/tests/mock_swsscommon.py
  sonic-chassisd/tests/test_chassisd.py
Labels: Request for 202106 branch

#195 [xcvrd] add debug logs for y_cable change events/probes
  sonic-xcvrd/xcvrd/xcvrd_utilities/y_cable_helper.py
Labels: Request for 202012 Branch, xcvrd
