Repository sonic-net/sonic-platform-daemons, pull requests merged in 2022-01, with the labels that each got.

#233 [voq][pmon]xcvrd process show backtrace in the syslog on VOQ linecard.
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd_utilities/port_mapping.py
Labels: Request for 202111 branch

#235 [psud] psud should log warning if PSU is in bad state before psud start up
  sonic-psud/scripts/psud
  sonic-psud/tests/test_DaemonPsud.py
  sonic-psud/tests/test_PsuStatus.py
Labels: Bug, Request for 202012 Branch, Request for 202106 branch, Request for 202111 branch

#219 [y_cable] refactor y_cable to a seperate logic and new daemon from xcvrd
  azure-pipelines.yml
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/tests/test_y_cable_helper.py
  sonic-xcvrd/xcvrd/xcvrd.py
  sonic-ycabled/pytest.ini
  sonic-ycabled/setup.cfg
  sonic-ycabled/setup.py
  sonic-ycabled/tests/__init__.py
  sonic-ycabled/tests/mock_swsscommon.py
  sonic-ycabled/tests/test_y_cable_helper.py
  sonic-ycabled/tests/test_ycable.py
  sonic-ycabled/ycable/__init__.py
  sonic-ycabled/ycable/ycable.py
  sonic-ycabled/ycable/ycable_utilities/__init__.py
  sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py
Labels: Y-Cable

#237 [y_cable] refactor y_cable to a seperate logic and new daemon from xcvrd
  azure-pipelines.yml
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
  sonic-ycabled/pytest.ini
  sonic-ycabled/setup.cfg
  sonic-ycabled/setup.py
  sonic-ycabled/tests/__init__.py
  sonic-ycabled/tests/mock_swsscommon.py
  sonic-ycabled/tests/test_y_cable_helper.py
  sonic-ycabled/tests/test_ycable.py
  sonic-ycabled/ycable/__init__.py
  sonic-ycabled/ycable/ycable.py
  sonic-ycabled/ycable/ycable_utilities/__init__.py
  sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py
Labels: Included in 202012 Branch
