Repository sonic-net/sonic-platform-daemons, pull requests merged in 2022-08, with the labels that each got.

#270 Xcvrd changes to support 400G ZR configuration
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: Chassis, CMIS

#279 [ycabled] add capability to enable/disable telemetry
  sonic-ycabled/tests/test_y_cable_helper.py
  sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py
Labels: Request for 202012 Branch, Request for 202205 branch

#281 Correct the peer forwarding state table
  sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py
Labels: Request for 202205 branch

#282 [ycabled] remove some spurious logs
  sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py
Labels: Request for 202205 branch
