Repository sonic-net/sonic-platform-daemons, pull requests merged in 2022-09, with the labels that each got.

#287 [ycabled] fix insert events from xcvrd;cleanup some mux toggle logic
  sonic-ycabled/tests/test_ycable.py
  sonic-ycabled/ycable/ycable.py
  sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py
Labels: Request for 202012 Branch, Request for 202205 branch

#289 [ycable] cleanup logic for creating grpc future ready
  sonic-ycabled/tests/test_y_cable_helper.py
  sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py
Labels: Y-Cable

#285 [Xcvrd] Soak duplicate events and process only updated interested events
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd_utilities/port_mapping.py
Labels: Enhancement, Chassis, Request for 202205 branch, CMIS

#286 Use get() to fetch default value from dictionary for port admin_status
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: Chassis, Request for 202205 branch
