Repository sonic-net/sonic-platform-daemons, pull requests merged in 2023-06, with the labels that each got.

#366 [xcvrd] Reduce vendor_key to vendor_name for media_settings lookup
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: Enhancement

#371 [dualtor] Fix command `show mux status`
  sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py
Labels: Request for 202205 branch

#372 [ycabled] correct the wrong function call for 'config hwmode state'
  sonic-ycabled/tests/test_y_cable_helper.py
  sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py
Labels: Request for 202205 branch, Request for 202211 branch

#363 [show][chassis]: Add support for serial field to show chassis module status CLI
  sonic-chassisd/scripts/chassisd
  sonic-chassisd/tests/mock_platform.py
  sonic-chassisd/tests/test_chassisd.py
Labels: Request for 202205 branch, Request for 202211 branch

#360 Separate periodic v/s fixed EEPROM reads between threads and optimize xcvrd boot-up time
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd_utilities/sfp_status_helper.py
Labels: Request for 202205 branch, Request for 202211 branch
