Repository sonic-net/sonic-platform-daemons, pull requests merged in 2023-04, with the labels that each got.

#342 Retrieve subport from CONFIG_DB to enable breakout support
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: Enhancement, Request for 202205 branch, CMIS, Request for 202211 branch

#335 Update xcvrd to use new STATE_DB FAST_REBOOT entry
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: xcvrd, Request for 202211 branch

#345 [CMIS] Add power up duration for power up timeout
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: Request for 202205 branch, CMIS, Request for 202211 branch
