Repository sonic-net/sonic-platform-daemons, pull requests merged in 2023-12, with the labels that each got.

#410 400ZR not linking up with latest SONiC master image
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: Bug, C-CMIS

#412 Mark sub-port interfaces as invalid ports in xcvrd
  sonic-xcvrd/xcvrd/xcvrd_utilities/port_mapping.py
Labels: Bug, xcvrd, Request for 202205 Branch, Request for 202305 Branch, Request for 202311 Branch

#413 [action] [PR:412] Mark sub-port interfaces as invalid ports in xcvrd (#412)
  sonic-xcvrd/xcvrd/xcvrd_utilities/port_mapping.py
Labels: automerge

#416 Support 800G ifname in xcvrd
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: xcvrd

#418 [action] [PR:378] Use vendor customizable fan speed threshold checks (#378)
  sonic-thermalctld/scripts/thermalctld
  sonic-thermalctld/tests/test_thermalctld.py
Labels: automerge
