Repository sonic-net/sonic-platform-daemons, pull requests merged in 2024-06, with the labels that each got.

#495 [action] [PR:493] Fix for #19116 [xcvrd] typo "log_notifce" results in port oper down (#493)
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: automerge

#497 [CMIS] Skip re-init flow for SW-controlled ports in case of fastboot
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: Request for 202311 Branch, Cherry Pick Conflict_202311

#499 [action] [PR:497] [CMIS] Skip re-init flow for SW-controlled ports in case of fastboot (#497)
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: automerge

#501 [xcvrd] Fix issue: do not print error log when module support non-ethernet application
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: Bug, Request for 202311 Branch, Request for 202405 Branch

#503 [xcvrd] change log content and log level when application is not found
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: Request for 202311 Branch, Cherry Pick Conflict_202311, Cherry Pick Conflict_202405, Request for 202405 Branch

#504 [action] [PR:501] [xcvrd] Fix issue: do not print error log when module support non-ethernet application (#501)
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: automerge

#506 [action] [PR:503] [xcvrd] change log content and log level when application is not found (#503)
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: automerge
