Repository sonic-net/sonic-platform-daemons, pull requests merged in 2024-07, with the labels that each got.

#511 Initialize application specific fields as 'N/A' in TRANSCEIVER_INFO table
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: xcvrd, Request for 202305 Branch, Cherry Pick Conflict_202305, Request for 202311 Branch, Request for 202405 Branch

#509 [ycabled][active-active] Fix in gRPC channel callback logic by creating swsscommon table within the context
  sonic-ycabled/tests/test_y_cable_helper.py
  sonic-ycabled/ycable/ycable.py
  sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py
  sonic-ycabled/ycable/ycable_utilities/y_cable_table_helper.py
Labels: Y-Cable, Request for 202305 Branch, Request for 202311 Branch, Request for 202405 Branch

#520 [action] [PR:511] Initialize application specific fields as 'N/A' in TRANSCEIVER_INFO table (#511)
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: automerge

#519 [action] [PR:511] Initialize application specific fields as 'N/A' in TRANSCEIVER_INFO table (#511)
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: automerge

#517 [action] [PR:509] [ycabled][active-active] Fix in gRPC channel callback logic by creating swsscommon table within the context (#509)
  sonic-ycabled/tests/test_y_cable_helper.py
  sonic-ycabled/ycable/ycable.py
  sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py
  sonic-ycabled/ycable/ycable_utilities/y_cable_table_helper.py
Labels: automerge

#516 [action] [PR:509] [ycabled][active-active] Fix in gRPC channel callback logic by creating swsscommon table within the context (#509)
  sonic-ycabled/tests/test_y_cable_helper.py
  sonic-ycabled/ycable/ycable.py
  sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py
  sonic-ycabled/ycable/ycable_utilities/y_cable_table_helper.py
Labels: automerge

#518 [action] [PR:509] [ycabled][active-active] Fix in gRPC channel callback logic by creating swsscommon table within the context (#509)
  sonic-ycabled/tests/test_y_cable_helper.py
  sonic-ycabled/ycable/ycable.py
  sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py
  sonic-ycabled/ycable/ycable_utilities/y_cable_table_helper.py
Labels: automerge

#513 [xcvrd] Fix SfpStateUpdateTask crash for RJ45 cable type
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: Request for 202405 Branch

#521 Remove redundant xcvr_table_helper init during CmisManagerTask init
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: xcvrd, Request for 202311 Branch, Request for 202405 Branch

#523 [action] [PR:521] Remove redundant xcvr_table_helper init during CmisManagerTask init (#521)
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: automerge

#522 [action] [PR:521] Remove redundant xcvr_table_helper init during CmisManagerTask init (#521)
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: automerge
