Repository sonic-net/sonic-platform-daemons, pull requests merged in 2024-09, with the labels that each got.

#537 [action] [PR:471] [xcvrd] Modify to support regular expression when parsing the key in media_settings.json (#471)
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd_utilities/media_settings_parser.py
Labels: automerge

#529 [PMON][psud] Fix the repeated NOTICE log message on Chassis platform
  sonic-psud/scripts/psud
  sonic-psud/tests/test_PsuChassisInfo.py
Labels: psud

#539 [xcvrd] Add logs to improve debugging in xcvrd
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: Request for 202311 Branch, Cherry Pick Conflict_202311, Request for 202405 Branch

#540 [action] [PR:539] [xcvrd] Add logs to improve debugging in xcvrd (#539)
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: automerge
