Repository sonic-net/sonic-platform-daemons, pull requests merged in 2024-03, with the labels that each got.

#426 [action] [PR:412] Mark sub-port interfaces as invalid ports in xcvrd (#412)
  sonic-xcvrd/xcvrd/xcvrd_utilities/port_mapping.py
Labels: automerge

#444 [action] [PR:440] Updated supported CMIS module types in xcvrd to include new module for SPC4 (#440)
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: automerge

#443 Enable periodic polling of TRANSCEIVER_FIRMWARE_INFO table in DomInfoUpdateTask
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: xcvrd, Cherry Pick Conflict_202205, Request for 202205 Branch, CMIS, Request for 202305 Branch, Cherry Pick Conflict_202305, Request for 202311 Branch

#383 Add deterministic link bring-up feature for SFF compliant modules
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/sff_mgr.py
  sonic-xcvrd/xcvrd/xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd_utilities/xcvr_table_helper.py
Labels: xcvrd

#447 [action] [PR:424] Combine psu presence/status update with data update (#424)
  sonic-psud/scripts/psud
  sonic-psud/tests/test_DaemonPsud.py
  sonic-psud/tests/test_psud.py
Labels: automerge

#448 [action] [PR:443] Enable periodic polling of TRANSCEIVER_FIRMWARE_INFO table in DomInfoUpdateTask (#443)
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: automerge

#449 Disable periodic polling of port in DomInfoUpdateTask thread during CMIS init
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: xcvrd, Request for 202305 Branch, Cherry Pick Conflict_202305, Request for 202311 Branch, Cherry Pick Conflict_202311

#453 [action] [PR:442] [ycabled] Fix insert delete events for ycabled OIR by subscribing to TRANSCEIVER_INFO instead of TRANSCEIVER_STATUS table (#442)
  sonic-ycabled/tests/test_ycable.py
  sonic-ycabled/ycable/ycable.py
  sonic-ycabled/ycable/ycable_utilities/y_cable_table_helper.py
Labels: automerge
