Repository sonic-net/sonic-platform-daemons, pull requests merged in 2024-05, with the labels that each got.

#483 Handling exceptions in CMIS SM to prevent xcvrd crash
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: xcvrd, P0

#482 [xcvrd] Fix issue: logical_port_name is not defined
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd_utilities/optics_si_parser.py
Labels: Bug, Request for 202311 Branch

#478 [ycabled] [active-standby] add changes for correcting telemetry values for 'active-standby' when the cable is present but vendor name and part number is not recognized
  sonic-ycabled/tests/test_y_cable_helper.py
  sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py
Labels: Request for 202205 Branch, Request for 202305 Branch, Request for 202311 Branch

#486 [action] [PR:478] [ycabled] [active-standby] add changes for correcting telemetry values for 'active-standby' when the cable is present but vendor name and part number is not recognized (#478)
  sonic-ycabled/tests/test_y_cable_helper.py
  sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py
Labels: automerge

#480 [chassis][midplane] Modify the chassisd to log expected/unexpected midplane connectivity messages
  sonic-chassisd/scripts/chassisd
  sonic-chassisd/tests/test_chassisd.py
Labels: Request for 202205 Branch, Request for 202305 Branch, Request for 202311 Branch

#488 [action] [PR:482] [xcvrd] Fix issue: logical_port_name is not defined (#482)
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd_utilities/optics_si_parser.py
Labels: automerge

#459 CMIS 'ConfigSuccess" failure while changing default ApSel code for 800G DR8/FR8 modules
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: Request for 202311 Branch

#490 [action] [PR:459] CMIS 'ConfigSuccess" failure while changing default ApSel code for 800G DR8/FR8 modules (#459)
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: automerge

#493 Fix for #19116 [xcvrd] typo "log_notifce" results in port oper down
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: Request for 202311 Branch
