Repository sonic-net/sonic-platform-daemons, pull requests merged in 2024-12, with the labels that each got.

#560 Fixed bug in chassisd causing incorrect number of ASICs in CHASSIS_STATE_DB
  sonic-chassisd/scripts/chassisd
  sonic-chassisd/tests/test_chassisd.py
Labels: Request for 202405 Branch

#569 [action] [PR:560] Fixed bug in chassisd causing incorrect number of ASICs in CHASSIS_STATE_DB (#560)
  sonic-chassisd/scripts/chassisd
  sonic-chassisd/tests/test_chassisd.py
Labels: automerge

#570 [action] [PR:558] [chassis][pmon] Fix the traceback issue while chassis is rebooting (#558)
  sonic-chassisd/scripts/chassisd
Labels: automerge

#555 thermalctld: Add support for fans on non-CPU modules
  sonic-thermalctld/scripts/thermalctld
  sonic-thermalctld/tests/mock_platform.py
  sonic-thermalctld/tests/test_thermalctld.py
Labels: Request for 202405 Branch

#571 [action] [PR:549] Reduce log level for lane speed key construction failure (#549)
  sonic-xcvrd/xcvrd/xcvrd_utilities/media_settings_parser.py
Labels: automerge

#565 Take non-CMIS xcvrs out of lpmode in SFF Manager
  sonic-xcvrd/xcvrd/sff_mgr.py
Labels: Chassis, Request for 202405 Branch

#576 [chassis][psud] Move the PSU parent information generation to the loop run function from the initialization function
  sonic-psud/scripts/psud
Labels: Request for 202405 Branch, Request for 202411 Branch

#573 [chassisd] Address the chassisd crash issue and add UT for it
  sonic-chassisd/scripts/chassisd
  sonic-chassisd/tests/test_chassisd.py
Labels: Request for 202405 Branch, Request for 202411 Branch

#578 [action] [PR:576] [chassis][psud] Move the PSU parent information generation to the loop run function from the initialization function (#576)
  sonic-psud/scripts/psud
Labels: automerge

#580 [action] [PR:573] [chassisd] Address the chassisd crash issue and add UT for it (#573)
  sonic-chassisd/scripts/chassisd
  sonic-chassisd/tests/test_chassisd.py
Labels: automerge

#581 [action] [PR:565] Take non-CMIS xcvrs out of lpmode in SFF Manager (#565)
  sonic-xcvrd/xcvrd/sff_mgr.py
Labels: automerge
