Repository sonic-net/sonic-platform-daemons, pull requests merged in 2024-10, with the labels that each got.

#533 Improve parsing of media-settings.json for non-CMIS and breakout ports
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd_utilities/media_settings_parser.py
Labels: Request for 202311 Branch, Cherry Pick Conflict_202311, Request for 202405 Branch

#543 [action] [PR:533] Improve parsing of media-settings.json for non-CMIS and breakout ports (#533)
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd_utilities/media_settings_parser.py
Labels: automerge

#544 [action] [PR:471] [xcvrd] Modify to support regular expression when parsing the key in media_settings.json (#471)
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd_utilities/media_settings_parser.py
Labels: automerge

#541 Xcvrd crash and restart should not cause link flap on platforms needing custom NPU SI settings
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd_utilities/media_settings_parser.py
  sonic-xcvrd/xcvrd/xcvrd_utilities/xcvr_table_helper.py
Labels: xcvrd, Cherry Pick Conflict_202405, Request for 202405 Branch

#547 [action] [PR:541] Xcvrd crash and restart should not cause link flap on platforms needing custom NPU SI settings (#541)
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd_utilities/media_settings_parser.py
  sonic-xcvrd/xcvrd/xcvrd_utilities/xcvr_table_helper.py
Labels: automerge

#552 Move DomInfoUpdateTask class to a separate file
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/dom_mgr.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: xcvrd, Request for 202405 Branch

#553 [action] [PR:552] Move DomInfoUpdateTask class to a separate file (#552)
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/dom_mgr.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: automerge
