Repository sonic-net/sonic-platform-daemons, pull requests merged in 2024-04, with the labels that each got.

#457 [action] [PR:442] [ycabled] Fix insert delete events for ycabled OIR by subscribing to TRANSCEIVER_INFO instead of TRANSCEIVER_STATUS table (#442)
  sonic-ycabled/tests/test_ycable.py
  sonic-ycabled/ycable/ycable.py
  sonic-ycabled/ycable/ycable_utilities/y_cable_table_helper.py
Labels: automerge

#461 Fix intermittent build failure for test_SfpStateUpdateTask_task_run_stop
  sonic-xcvrd/tests/test_xcvrd.py
Labels: Cherry Pick Conflict_202205, Request for 202205 Branch, Request for 202305 Branch, Cherry Pick Conflict_202305, Request for 202311 Branch, Cherry Pick Conflict_202311

#456 Support to get MEDIA_SETTING and OPTICS_SI from both platform folder and HWSKU folder
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd_utilities/media_settings_parser.py
  sonic-xcvrd/xcvrd/xcvrd_utilities/optics_si_parser.py
Labels: Request for 202311 Branch, Cherry Pick Conflict_202311

#462 [chassis][linecard] Fix Module LINECARD<> went off-line message for empty slot issue
  sonic-chassisd/scripts/chassisd
  sonic-chassisd/tests/test_chassisd.py
Labels: Request for 202205 Branch, Request for 202305 Branch

#469 [action] [PR:462] [chassis][linecard] Fix Module LINECARD<> went off-line message for empty slot issue (#462)
  sonic-chassisd/scripts/chassisd
  sonic-chassisd/tests/test_chassisd.py
Labels: automerge

#470 [action] [PR:462] [chassis][linecard] Fix Module LINECARD<> went off-line message for empty slot issue (#462)
  sonic-chassisd/scripts/chassisd
  sonic-chassisd/tests/test_chassisd.py
Labels: automerge

#472 [action] [PR:374] [ci] Migrate agent pool to self hosted pool (#374)
  azure-pipelines.yml
Labels: automerge

#476 [action] [PR:462] [chassis][linecard] Fix Module LINECARD<> went off-line message for empty slot issue (#462)
  sonic-chassisd/scripts/chassisd
  sonic-chassisd/tests/test_chassisd.py
Labels: automerge
