Repository sonic-net/sonic-platform-daemons, pull requests merged in 2025-06, with the labels that each got.

#620 [action] [PR:619] [Smartswitch][chassisd] Addition of pre shutdown and post startup function calls
  sonic-chassisd/scripts/chassisd
  sonic-chassisd/tests/mock_platform.py
  sonic-chassisd/tests/test_chassisd.py
Labels: automerge

#618 Add Robust Exception Handling to pcied Daemon for Improved Stability
  sonic-pcied/scripts/pcied
  sonic-pcied/tests/mocked_libs/sonic_platform/pcie.py
  sonic-pcied/tests/test_DaemonPcied.py
  sonic-pcied/tests/test_pcied.py
Labels: Request for 202411 Branch, Cherry Pick Conflict_202411, Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412, Request for 202505 Branch

#625 [action] [PR:618] Add Robust Exception Handling to pcied Daemon for Improved Stability
  sonic-pcied/scripts/pcied
  sonic-pcied/tests/mocked_libs/sonic_platform/pcie.py
  sonic-pcied/tests/test_DaemonPcied.py
  sonic-pcied/tests/test_pcied.py
Labels: automerge

#606 [Smartswitch] Fix incorrect reporting of data plane and control plane by DPU
  sonic-chassisd/scripts/chassisd
  sonic-chassisd/tests/mock_swsscommon.py
  sonic-chassisd/tests/test_chassisd.py
  sonic-chassisd/tests/test_dpu_chassisd.py
Labels: Request for 202505 Branch

#616 xcvrd: Remove SFP API object when SFP is removed
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: Request for 202411 Branch, Request for msft-202412 Branch, Request for 202505 Branch

#627 [action] [PR:616] xcvrd: Remove SFP API object when SFP is removed
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: automerge

#634 [action] [PR:629] [Smartswitch][Chassisd] Fix for initialization DPU admin state post startup and pre shutdown
  sonic-chassisd/scripts/chassisd
  sonic-chassisd/tests/test_chassisd.py
Labels: automerge

#607 Chassisd does not wait for the execution to complete for previous admin state change requests. Fixed issue #22138
  sonic-chassisd/scripts/chassisd
  sonic-chassisd/tests/mock_swsscommon.py
  sonic-chassisd/tests/test_chassisd.py
Labels: Request for 202505 Branch
