Repository sonic-net/sonic-platform-daemons, pull requests merged in 2025-05, with the labels that each got.

#604 [xcvrd] Re-organize transceiver DOM and STATUS tables + enable link event handling for DOM monitoring + DOM polling based on physical port
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/dom/dom_mgr.py
  sonic-xcvrd/xcvrd/dom/utilities/db/utils.py
  sonic-xcvrd/xcvrd/dom/utilities/dom_sensor/__init__.py
  sonic-xcvrd/xcvrd/dom/utilities/dom_sensor/db_utils.py
  sonic-xcvrd/xcvrd/dom/utilities/dom_sensor/utils.py
  sonic-xcvrd/xcvrd/dom/utilities/status/__init__.py
  sonic-xcvrd/xcvrd/dom/utilities/status/db_utils.py
  sonic-xcvrd/xcvrd/dom/utilities/status/utils.py
  sonic-xcvrd/xcvrd/dom/utilities/vdm/db_utils.py
  sonic-xcvrd/xcvrd/dom/utilities/vdm/utils.py
  sonic-xcvrd/xcvrd/sff_mgr.py
  sonic-xcvrd/xcvrd/xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd_utilities/port_event_helper.py
  sonic-xcvrd/xcvrd/xcvrd_utilities/sfp_status_helper.py
  sonic-xcvrd/xcvrd/xcvrd_utilities/xcvr_table_helper.py
Labels: xcvrd, Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412

#613 [xcvrd] do not wait state change while calling cmis.set_lpmode
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: Request for msft-202412 Branch

#611 [xcvrd] Optimize module initialization performance
  sonic-xcvrd/tests/mock_swsscommon.py
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412
