Repository sonic-net/sonic-platform-daemons, pull requests merged in 2025-09, with the labels that each got.

#670 [action] [PR:653] Check low power mode before vdm handling
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/dom/dom_mgr.py
  sonic-xcvrd/xcvrd/xcvrd_utilities/utils.py
Labels: automerge

#672 [xcvrd] Improve logging in case of unable to find appropriate match for optic SI settings
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd_utilities/optics_si_parser.py
Labels: xcvrd, Request for 202505 Branch, Cherry Pick Conflict_202505

#679 Handle restore_count and system_enable ”NoneType“ value scenario.
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: Request for 202505 Branch, Cherry Pick Conflict_202505
