Repository sonic-net/sonic-platform-daemons, pull requests merged in 2025-07, with the labels that each got.

#637 [action] [PR:607] Chassisd does not wait for the execution to complete for previous admin state change requests. Fixed issue #22138
  sonic-chassisd/scripts/chassisd
  sonic-chassisd/tests/mock_swsscommon.py
  sonic-chassisd/tests/test_chassisd.py
Labels: automerge

#636 [action] [PR:632] Catch the xcvrd exception returned by get_transceiver_info
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: automerge

#633 [Smartswitch][pcied] Fix pcied handling for smartswitch during DPU detach #5
  sonic-pcied/scripts/pcied
  sonic-pcied/tests/test_DaemonPcied.py
Labels: Request for 202505 Branch

#641 [action] [PR:633] [Smartswitch][pcied] Fix pcied handling for smartswitch during DPU detach #5
  sonic-pcied/scripts/pcied
  sonic-pcied/tests/test_DaemonPcied.py
Labels: automerge

#647 Fix incorrect string formatting for PCIe device name
  sonic-pcied/scripts/pcied
Labels: Request for 202505 Branch

#648 [action] [PR:647] Fix incorrect string formatting for PCIe device name
  sonic-pcied/scripts/pcied
Labels: automerge

#608 Add CMIS FSM for DP decomission
  sonic-xcvrd/tests/test_xcvrd.py
  sonic-xcvrd/xcvrd/xcvrd.py
Labels: Cherry Pick Conflict_msft-202412, Request for 202505 Branch

#631 Fix for 22430 - SmartSwitch - Reboot cause for DPUs not updated on complete system reboot
  sonic-chassisd/scripts/chassisd
  sonic-chassisd/tests/test_chassisd.py
Labels: Request for 202505 Branch
